version: '3'
services:
  rails:
      image: ruby:2.5.5
      hostname: "${PROJECT_NAME}_rails"
      container_name: "${PROJECT_NAME}_rails"
      ports:
        - "${RAILS_PORT}:3000"
      volumes:
        - "./${PROJECT_ROOT}:/usr/src/app"
      environment:
        RAILS_ENV: "${RAILS_ENV}"
        DB_HOST: "${DB_HOSTNAME}"
        DB_NAME: "${DB}"
        DB_TEST_NAME: "${DB_TEST}"
        DB_PASSWORD: "${DB_PASS}"
        DB_USERNAME: "${DB_USER}"
        APPLICATION_NAME: "${APPLICATION_NAME}"
        APPLICATION_VERSION: "${APPLICATION_VERSION}"
        BASE_PATH: "${BASE_PATH}"
        SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
        RAILS_SERVE_STATIC_FILES: "${RAILS_SERVE_STATIC_FILES}"
      working_dir: /usr/src/app
      links:
        - postgresql
      entrypoint: ./postinstall

  postgresql:
      image: postgres
      hostname: "${PROJECT_NAME}_db"
      container_name: "${PROJECT_NAME}_db"
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
          POSTGRES_DB: "${DB}"
          POSTGRES_USER: "${DB_USER}"
          POSTGRES_PASSWORD: "${DB_PASS}"
volumes:
  db-data:
