source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '2.5.5'

gem 'active_model_serializers', '~> 0.10.6'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'devise'
gem 'dotenv-rails'
gem 'json-schema'
gem 'jwt'
gem 'paranoia', '~> 2.2'
gem 'pg'
gem 'rack-cors'
gem 'rails', '~> 5.1.3'
gem 'rails_param'
gem 'rolify'
gem 'rubocop', '~> 0.72.0', require: false
gem 'swagger-blocks'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 3.5'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'fabrication'
  gem 'json_matchers'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
